# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c5c59ec51bc41c49218b747cb64e8e0d76119d962b78a1b06ee12d08986304db8838cdda5a14ccebb71a5b9e343282826c59a46e5f1f0d412f48d845b75a903

test:
  secret_key_base: f2ed1940fd8c403ecf5cdc1a4edc86be4468fe66e97e6ea21d3c73a9df74da25403858eabe2214f31bd601ba9129b8db1c91367ab3f20248c2b9cd8ce342f317

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
